### ISSUE TITLE
Fails to compile with icc

### ISSUE THREAD

**Issue by certik** [python-cmake-buildsystem/python-cmake-buildsystem#269]
I tried to build using Intel icc version 19.1.0.20191121 and the cmake succeeds to run:
```
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/builds/certik/truchas/scratch/python-install ../python-cmake-buildsystem
-- The C compiler identification is Intel 19.1.0.20191121
-- The ASM compiler identification is Intel
-- Found assembler: /opt/intel/bin/icc
-- Check for working C compiler: /opt/intel/bin/icc
-- Check for working C compiler: /opt/intel/bin/icc -- works
-- Detecting C compiler ABI info
...
-- Configuring done
-- Generating done
-- Build files have been written to: /builds/certik/truchas/scratch/python-build
```
But when I run `make`, it fails:
```
$ make -j8
...
[ 31%] Building C object CMakeBuild/libpython/CMakeFiles/pgen.dir/builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c.o
/builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c(37): error: expected an expression
          for (int j = 0; j < g->g_dfa[i].d_nstates; j++)
               ^
/builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c(37): error: identifier "j" is undefined
          for (int j = 0; j < g->g_dfa[i].d_nstates; j++)
                          ^
compilation aborted for /builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c (code 2)
make[2]: *** [CMakeBuild/libpython/CMakeFiles/pgen.dir/builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c.o] Error 2
```

It looks like the icc compiler does not allow to define variables inside the for loop.

I don't know if icc is supported, but if not, then I would expect cmake to error out sooner. It might also be possible to fix the failures with a patch.

**Comment by dand-oss** [comment]
The problem is in the source code

If this is python dist source code, your options include
- patch the python source for icc compatability
- apply some options in cmake to allow icc to handle this
- look in python for icc support in the python build

**Comment by telamonian** [comment]
Apparently, variable-definition-in-loop was a feature added to the C language as part of the C99. Whereas even the most modern version of `icc` for some questionable reason defaults to "C90 plus GNU extensions". See [the icc docs](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/language-options/std-qstd.html) and this [SO](https://stackoverflow.com/a/54628718/425458).

So it looks like the fix for this will be to set the `-std=c99` CFLAG for intel toolchain builds

**Comment by telamonian** [comment]
Probably will need something in a CMake file like:

```cmake
if(${CMAKE_CXX_COMPILER_ID} MATCHES "Intel")
    SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99")
endif(${CMAKE_CXX_COMPILER_ID} MATCHES "Intel")
```

**Comment by telamonian** [comment]
@certik I did a fix PR at #271. Can you please try it out?
