### ISSUE TITLE
Unable to create static Python 3 on CentOS 6.10 with CMake 3.12.4

### ISSUE THREAD

**Issue by meleschi** [python-cmake-buildsystem/python-cmake-buildsystem#237]
I see the following issue with attempting to make a static Python build using CMake 3.12.4:

 51%] Building C object CMakeBuild/libpython/CMakeFiles/_freeze_importlib.dir/home/vagrant/scratch/Python-3.6.4/Modules/tkappinit.c.o
[ 51%] Building C object CMakeBuild/libpython/CMakeFiles/_freeze_importlib.dir/home/vagrant/scratch/Python-3.6.4/Modules/_tkinter.c.o
[ 51%] Building C object CMakeBuild/libpython/CMakeFiles/_freeze_importlib.dir/home/vagrant/scratch/Python-3.6.4/Modules/zlibmodule.c.o
[ 51%] Linking C executable _freeze_importlib
/usr/local/bin/ld: CMakeFiles/_freeze_importlib.dir/home/vagrant/scratch/Python-3.6.4/Modules/_cursesmodule.c.o: undefined reference to symbol 'halfdelay'
/usr/local/bin/ld: /lib64/libtinfo.so.5: error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
make[2]: *** [CMakeBuild/libpython/_freeze_importlib] Error 1
make[1]: *** [CMakeBuild/libpython/CMakeFiles/_freeze_importlib.dir/all] Error 2
make: *** [all] Error 2

It looks like -ltinfo is not properly being added to LIBS.  The version of ncurses that comes with Centos 6.10 requires the tinfo library to be passed, but I cannot find the proper place to define this.

Please see "https://github.com/hishamhm/htop/issues/198" for more information on why tinfo is required with some ncurses compiles.

Recompiling ncurses and putting it into /usr/local/ should help, but cmake keeps finding the original ncurses first and using those libraries.

**Comment by jcfr** [comment]
Thanks for the report :+1: 

>  tinfo is required with some ncurses compiles.

The tinfo library is looked up here:

https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/c3b8d532242efed85fb3cd77b0e39e424b6db475/cmake/ConfigureChecks.cmake#L41

Then the tinfo library is linked in the curses module here:

https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/c3b8d532242efed85fb3cd77b0e39e424b6db475/cmake/extensions/CMakeLists.txt#L575-L588


If you inspect the `CMakeCache.txt` file found in the build tree, what is the value of associated with the `TINFO_LIBRARY` cache entry ?

**Comment by meleschi** [comment]
Thank you for your speedy reply!

TINFO_LIBRARY is not in CMakeCache.txt.

[vagrant@localhost python-build]$ grep TINFO CMakeCache.txt
HAVE_SIGWAITINFO:INTERNAL=1

I believe cmake is not properly identifying the need for TINFO, but I'm no CMake expert!  Is there anything else I could paste here to help troubleshoot?

I was thinking it's something funny in 3.12.4's FindCurses.cmake file but I couldn't puzzle out what...

**Comment by jcfr** [comment]
You could try to turn the option `USE_SYSTEM_Curses` to `ON`

How could I best reproduce the issue ? Would using the `centos:centos6.10` docker image be a good approach ?
