### ISSUE TITLE
A patch to build with Visual Studio 2015

### ISSUE THREAD

**Issue by dzenanz** [python-cmake-buildsystem/python-cmake-buildsystem#161]
This is a patch to make Python 2.7.11 build on VS2015:

```
From 4ab220c38c7d15192ed3b394f47e4196c947f056 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?D=C5=BEenan=20Zuki=C4=87?= <dzenan.zukic@kitware.com>
Date: Mon, 24 Oct 2016 09:13:30 -0400
Subject: [PATCH] Build with VS2015

---
 Modules/posixmodule.c | 36 +++++-------------------------------
 Modules/timemodule.c  |  8 ++++----
 2 files changed, 9 insertions(+), 35 deletions(-)

diff --git a/Modules/posixmodule.c b/Modules/posixmodule.c
index 4fc3ef7..d90953f 100644
--- a/Modules/posixmodule.c
+++ b/Modules/posixmodule.c
@@ -570,38 +570,12 @@ extern __declspec(dllimport) char * __pioinfo[];
 int
 _PyVerify_fd(int fd)
 {
-    const int i1 = fd >> IOINFO_L2E;
-    const int i2 = fd & ((1 << IOINFO_L2E) - 1);

-    static int sizeof_ioinfo = 0;
-
-    /* Determine the actual size of the ioinfo structure,
-     * as used by the CRT loaded in memory
-     */
-    if (sizeof_ioinfo == 0 && __pioinfo[0] != NULL) {
-        sizeof_ioinfo = _msize(__pioinfo[0]) / IOINFO_ARRAY_ELTS;
-    }
-    if (sizeof_ioinfo == 0) {
-        /* This should not happen... */
-        goto fail;
-    }
-
-    /* See that it isn't a special CLEAR fileno */
-    if (fd != _NO_CONSOLE_FILENO) {
-        /* Microsoft CRT would check that 0<=fd<_nhandle but we can't do that.  Instead
-         * we check pointer validity and other info
-         */
-        if (0 <= i1 && i1 < IOINFO_ARRAYS && __pioinfo[i1] != NULL) {
-            /* finally, check that the file is open */
-            my_ioinfo* info = (my_ioinfo*)(__pioinfo[i1] + i2 * sizeof_ioinfo);
-            if (info->osfile & FOPEN) {
-                return 1;
-            }
-        }
-    }
-  fail:
-    errno = EBADF;
-    return 0;
+    //a call to _get_osfhandle with invalid fd sets errno to EBADF
+    if (_get_osfhandle(fd) == INVALID_HANDLE_VALUE)
+        return 0;
+    else
+        return 1;
 }

 /* the special case of checking dup2.  The target fd must be in a sensible range */
diff --git a/Modules/timemodule.c b/Modules/timemodule.c
index 12c43b0..8692080 100644
--- a/Modules/timemodule.c
+++ b/Modules/timemodule.c
@@ -710,7 +710,7 @@ inittimezone(PyObject *m) {
 #ifdef PYOS_OS2
     PyModule_AddIntConstant(m, "timezone", _timezone);
 #else /* !PYOS_OS2 */
-    PyModule_AddIntConstant(m, "timezone", timezone);
+    PyModule_AddIntConstant(m, "timezone", _timezone);
 #endif /* PYOS_OS2 */
 #ifdef HAVE_ALTZONE
     PyModule_AddIntConstant(m, "altzone", altzone);
@@ -718,12 +718,12 @@ inittimezone(PyObject *m) {
 #ifdef PYOS_OS2
     PyModule_AddIntConstant(m, "altzone", _timezone-3600);
 #else /* !PYOS_OS2 */
-    PyModule_AddIntConstant(m, "altzone", timezone-3600);
+    PyModule_AddIntConstant(m, "altzone", _timezone-3600);
 #endif /* PYOS_OS2 */
 #endif
-    PyModule_AddIntConstant(m, "daylight", daylight);
+    PyModule_AddIntConstant(m, "daylight", _daylight);
     PyModule_AddObject(m, "tzname",
-                       Py_BuildValue("(zz)", tzname[0], tzname[1]));
+                       Py_BuildValue("(zz)", _tzname[0], _tzname[1]));
 #else /* !HAVE_TZNAME || __GLIBC__ || __CYGWIN__*/
 #ifdef HAVE_STRUCT_TM_TM_ZONE
     {
-- 
2.9.0.windows.1
```

**Comment by Neurrone** [comment]
Could you make one for python 3.5.2 as well?

**Comment by dzenanz** [comment]
I was under the impression that Python 3.5 supports VS2015 officially.

**Comment by dzenanz** [comment]
Python 2.7.13 fails to build on VS2015 too: `Python-2.7.13\Modules\timemodule.c(713): error C2065: 'timezone': undeclared identifier`. Should we turn this patch into a PR?

**Comment by jcfr** [comment]
> Should we turn this patch into a PR?

That makes sense. At least a PR for this `python-cmake-buildsystem`. The reality is that we need a staging area for patches waiting their are integrated upstream. And sometimes, patches are very specific to a system (e.g andoid, emscripten, ...) and generalizing them is not always feasible given the time and resources at hand.

Here is what I suggest:

1. Add a "cpython-patches" top level folder to this project
2. Patch for each version would be organized in folder like:

  ```
  <root>/cpython-patches/X.Y.Z/
  ```

  where  `X.Y.Z` corresponds to the python version

  Patch specific to a *system* (e.g android, arm, windows, ...) would be added in sub-directories like:

  ```
  <root>/cpython-patches/X.Y.Z/<system>
  ```
  
3. Add a README file `<root>/cpython-patches/X.Y.Z/README.md` describing motivation for each patches, give credit to original sources, ... 

4. Add a CMake option named `APPLY_CPYTHON_PATCH` that would be `OFF` by default

5. Patched would be applied if an executable `patch` is found on the system. Unix system all have it, and on windows system using Git Bash, it is reasonable requirements.

Note that we would gradually deprecate/update/remove patches found in `cmake/patches` and `cmake/patches-win32` and organize them as described above.

**Comment by ihnorton** [comment]
For the first patch, consider [this](https://mail.python.org/pipermail/python-checkins/2015-March/134824.html) if you want to support pre-VS2013.

I'm not sure if the second one will compile on *nix. You could use: https://chromium.googlesource.com/external/webrtc.git/+/5d55c98cd24ef161b80c69e20cd9b0512d2f2179%5E%21/#F0

**Comment by thewtex** [comment]
Side note: the [CPython's Developer's Guide](https://docs.python.org/devguide/) is a reference to keep in mind. Each `README.md` could be accompanied by a bugs.python.org (*bpo*) issue link and a GitHub PR.

**Comment by dzenanz** [comment]
I created a [bug report](http://bugs.python.org/issue30742) and made a [pull request](https://github.com/python/cpython/pull/2446).

**Comment by dzenanz** [comment]
The PR was rejected. I suppose we should switch to Python3 instead of clinging onto 2.7.

**Comment by jcfr** [comment]
Thanks for proposing the patch to upstream cpython. 

>  I suppose we should switch to Python3 instead of clinging onto 2.7.

Ideally yes.

If not yes possible, maintaining the patch here would be an intermediate solution.

**Comment by jcfr** [comment]
@thewtex As a preview here is a topic when I introduced the simple patch management system described above. See https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/compare/master...jcfr:fix-py27-vs2015-build-and-add-patch-mgmt

@dzenanz It will soon include all required patches to build CPython using VS2015.

Stay tuned

**Comment by thewtex** [comment]
@jcfr Cool!

**Comment by dzenanz** [comment]
@jcfr I don't see the `timezone` fix in that [PR](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/compare/master...jcfr:fix-py27-vs2015-build-and-add-patch-mgmt). Was that fixed before, elsewhere?

**Comment by jcfr** [comment]
@dzenanz Thanks for the review. 

It is indeed missing, I will add it today.

**Comment by jcfr** [comment]
Closing. This will be fixed by #188

**Comment by 0310gupta** [comment]
getting _imp__pioinfo unresolved external symbol, in posixmodule.c while compiling in Visual Studio 2015? any suggestion

**Comment by theclashingfritz** [comment]
^ Bump

**Comment by theclashingfritz** [comment]
Fixed it by removing extern __declspec(dllimport) char * __pioinfo[]; which isn't used in the new patch

**Comment by MagicRedDeer** [comment]
Sorry for some issue necromancy. I have recently built the python 2.7.11 using visual studio 2019 and PlatformToolset v140. You need to apply the following patch to have wide character input support in the module `msvcrt`.

`
From a932b2f4356105f8abcfd369239f8e86d8a41b3a Mon Sep 17 00:00:00 2001
From: Talha Ahmed <talha.ahmed@gmail.com>
Date: Thu, 13 Jun 2019 19:46:05 +0500
Subject: [PATCH 2/2] removing _WCONIO_DEFINED check

---
 PC/msvcrtmodule.c | 10 ----------
 1 file changed, 10 deletions(-)

diff --git a/PC/msvcrtmodule.c b/PC/msvcrtmodule.c
index 057900d..d24c8c4 100644
--- a/PC/msvcrtmodule.c
+++ b/PC/msvcrtmodule.c
@@ -205,7 +205,6 @@ was a special function key, this will return '\\000' or '\\xe0'; the next\n\
 call will return the keycode. The Control-C keypress cannot be read with\n\
 this function.");
 
-#ifdef _WCONIO_DEFINED
 static PyObject *
 msvcrt_getwch(PyObject *self, PyObject *args)
 {
@@ -226,7 +225,6 @@ PyDoc_STRVAR(getwch_doc,
 "getwch() -> Unicode key character\n\
 \n\
 Wide char variant of getch(), returning a Unicode value.");
-#endif
 
 static PyObject *
 msvcrt_getche(PyObject *self, PyObject *args)
@@ -250,7 +248,6 @@ PyDoc_STRVAR(getche_doc,
 Similar to getch(), but the keypress will be echoed if it represents\n\
 a printable character.");
 
-#ifdef _WCONIO_DEFINED
 static PyObject *
 msvcrt_getwche(PyObject *self, PyObject *args)
 {
@@ -271,7 +268,6 @@ PyDoc_STRVAR(getwche_doc,
 "getwche() -> Unicode key character\n\
 \n\
 Wide char variant of getche(), returning a Unicode value.");
-#endif
 
 static PyObject *
 msvcrt_putch(PyObject *self, PyObject *args)
@@ -291,7 +287,6 @@ PyDoc_STRVAR(putch_doc,
 \n\
 Print the character char to the console without buffering.");
 
-#ifdef _WCONIO_DEFINED
 static PyObject *
 msvcrt_putwch(PyObject *self, PyObject *args)
 {
@@ -315,7 +310,6 @@ PyDoc_STRVAR(putwch_doc,
 "putwch(unicode_char) -> None\n\
 \n\
 Wide char variant of putch(), accepting a Unicode value.");
-#endif
 
 static PyObject *
 msvcrt_ungetch(PyObject *self, PyObject *args)
@@ -337,7 +331,6 @@ PyDoc_STRVAR(ungetch_doc,
 Cause the character char to be \"pushed back\" into the console buffer;\n\
 it will be the next character read by getch() or getche().");
 
-#ifdef _WCONIO_DEFINED
 static PyObject *
 msvcrt_ungetwch(PyObject *self, PyObject *args)
 {
@@ -356,7 +349,6 @@ PyDoc_STRVAR(ungetwch_doc,
 "ungetwch(unicode_char) -> None\n\
 \n\
 Wide char variant of ungetch(), accepting a Unicode value.");
-#endif
 
 static void
 insertint(PyObject *d, char *name, int value)
@@ -385,12 +377,10 @@ static struct PyMethodDef msvcrt_functions[] = {
     {"getche",                  msvcrt_getche, METH_VARARGS, getche_doc},
     {"putch",                   msvcrt_putch, METH_VARARGS, putch_doc},
     {"ungetch",                 msvcrt_ungetch, METH_VARARGS, ungetch_doc},
-#ifdef _WCONIO_DEFINED
     {"getwch",                  msvcrt_getwch, METH_VARARGS, getwch_doc},
     {"getwche",                 msvcrt_getwche, METH_VARARGS, getwche_doc},
     {"putwch",                  msvcrt_putwch, METH_VARARGS, putwch_doc},
     {"ungetwch",                msvcrt_ungetwch, METH_VARARGS, ungetwch_doc},
-#endif
     {NULL,                      NULL}
 };
 
-- 
2.9.0.windows.1

`
