### PR TITLE
Fix #269: add C99 flag for intel compilers

### LINKED ISSUE #269: Fails to compile with icc
I tried to build using Intel icc version 19.1.0.20191121 and the cmake succeeds to run:
```
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/builds/certik/truchas/scratch/python-install ../python-cmake-buildsystem
-- The C compiler identification is Intel 19.1.0.20191121
-- The ASM compiler identification is Intel
-- Found assembler: /opt/intel/bin/icc
-- Check for working C compiler: /opt/intel/bin/icc
-- Check for working C compiler: /opt/intel/bin/icc -- works
-- Detecting C compiler ABI info
...
-- Configuring done
-- Generating done
-- Build files have been written to: /builds/certik/truchas/scratch/python-build
```
But when I run `make`, it fails:
```
$ make -j8
...
[ 31%] Building C object CMakeBuild/libpython/CMakeFiles/pgen.dir/builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c.o
/builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c(37): error: expected an expression
          for (int j = 0; j < g->g_dfa[i].d_nstates; j++)
               ^
/builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c(37): error: identifier "j" is undefined
          for (int j = 0; j < g->g_dfa[i].d_nstates; j++)
                          ^
compilation aborted for /builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c (code 2)
make[2]: *** [CMakeBuild/libpython/CMakeFiles/pgen.dir/builds/certik/truchas/scratch/Python-3.6.7/Parser/grammar.c.o] Error 2
```

It looks like the icc compiler does not allow to define variables inside the for loop.

I don't know if icc is supported, but if not, then I would expect cmake to error out sooner. It might also be possible to fix the failures with a patch.

### PR DESCRIPTION
**Pull request by telamonian**
The intel C compiler [defaults to `-std=gnu98`](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/language-options/std-qstd.html#std-qstd_GUID-338F4C2A-560C-4338-8ACF-C4B022A7C865), which apparently causes problems with recent cpython source. Judging by the existing code in `CMakeLists.txt` and [this issue on the core cpython repo](https://github.com/python/cpython/pull/568), somewhere around cpy3.6 cpython moved on to C99.

This PR ensures that if intel compilers are being used on cpy>=3.6 source, the `-std=C99` flag will be added

### CODE REVIEW

**Comment by telamonian** [comment]
@certik It's been a while since I've had personal access to the intel compiler suite, so I have no actual way of testing this PR out myself. However, I'm pretty sure it will solve your problem? Can you please try it out and let us know?

**Comment by certik** [comment]
Thanks, I'll give it a shot soon!

**Comment by concatime** [comment]
Why not simply add `set(CMAKE_C_STANDARD 99)` ?

**Comment by concatime** [comment]
Or a simple patch:
```diff
diff --git a/Parser/grammar.c b/Parser/grammar.c
index 75fd5b9cde..1a4d585026 100644
--- a/Parser/grammar.c
+++ b/Parser/grammar.c
@@ -33,8 +33,9 @@ freegrammar(grammar *g)
 {
     int i;
     for (i = 0; i < g->g_ndfas; i++) {
+        int j;
         free(g->g_dfa[i].d_name);
-        for (int j = 0; j < g->g_dfa[i].d_nstates; j++)
+        for (j = 0; j < g->g_dfa[i].d_nstates; j++)
             PyObject_FREE(g->g_dfa[i].d_state[j].s_arc);
         PyObject_FREE(g->g_dfa[i].d_state);
     }
```
